library("igraph")
karate = graph.famous("Zachary")
ebc = edge.betweenness.community(karate)
cut = cutat(ebc,3)
colors = rainbow(3)
plot(karate, vertex.color=colors[cut])
cut = cutat(ebc,4)
colors = rainbow(4)
plot(karate, vertex.color=colors[cut])
cut = cutat(ebc,5)
colors = rainbow(5)
plot(karate, vertex.color=colors[cut])
